### ISSUE TITLE
Login page and auth token

### ISSUE THREAD

**Issue by KrisBraun** [SanctuaryRefugeeHealth/sanctuary-patient-app#3]
- [x] Add a login page with email and password.
- [x] Request an auth token from `/auth` with `{email, password}`
- [x] Display "Incorrect email or password" on `401` and "Problem logging in" on any other error status
- [x] On success, set the `x-access-token` header (using middleware / interceptor) to the `token` field of the response

**Comment by jaeyp** [comment]
https://github.com/KrisBraun/sanctuary-patient-app/pull/4
