### ISSUE TITLE
Update message template

### ISSUE THREAD

**Issue by KrisBraun** [SanctuaryRefugeeHealth/sanctuary-patient-app#36]
Sanctuary has provided an updated message template, and will provide translations shortly. This will of course require adjusting the forms, too.

> Dear ( ), this message is to inform you of your upcoming appointment: ( ).
> Date: ( )
> Time: ( )
> Address: ( )
> Special Notes: ( )
> 
> If you have any questions, please call Sanctuary Refugee Health Centre (Dr. Michael Stephenson) at 226-336-1321.

**Comment by KrisBraun** [comment]
A corresponding API issue will need to be created. I haven't gone through the API/schema to figure out the changes, so perhaps the person taking this issue could create that issue.

**Comment by Wiles** [comment]
`Dear ( ), this message is to inform you of your upcoming appointment: ( ).`

What is meant to go into the second placeholder here?

`Special Notes: ( )`

What is this used for? I do not remember seeing notes before.

**Comment by Wiles** [comment]
> Please confirm your attendance by replying “yes” or “no”.
> If you need an interpreter, please reply with the word "interpreter".

Should these be included now before we have support for handling replies?

**Comment by KrisBraun** [comment]
I have a meeting with Shukri tomorrow so can get more details. The fields in the form will definitely need to change. In fact, in the current version, several of the form fields don't map to anything in the current (old) template.

My guess at this point is that the second placeholder is a free-form description of the appointment, which replaces the practitioner name and clinic name. Examples could include "Chest x-rays", "Consultation with Dr Smith".

Special notes is new, and optional.

**Comment by KrisBraun** [comment]
You're right that we should hold back adding the part about replies until we support them.

**Comment by Wiles** [comment]
Alright, I will hold off on this until after your meeting.

**Comment by KrisBraun** [comment]
@Wiles Spoke with Shukri about the fields in the new template. The second placeholder should be "Appointment" or "Appointment description". "Special Notes:" is new and optional (i.e. collect it in form, skip it in template if blank).

**Comment by Wiles** [comment]
The current form is something like this:

- Patient
  - patient name
  - patient phone number
  - patient language
- Clinic Information
  - clinic name
  - Specialist name
  - specialist phone number
  - address
- Appointment Information
  - appointment date
  - appointment time

What is needed now is:

- Patient
  - patient name
  - patient phone number
  - patient language
- Appointment Information
  - address
  - appointment description
  - appointment date
  - appointment time
  - special notes

@KrisBraun Does that look right/appropriate to you?

**Comment by Wiles** [comment]
Do they still want to collect fields that are not included in the message (clinic name, specialist, etc)?

**Comment by KrisBraun** [comment]
Yes, new form looks good. I'd swap appointment address and description (i.e. description first). All other existing fields not in the message should be removed from the form. Thanks!
